const musics =[
    {
        id: 0,
        number: '01',
        file:'actdm.mp3',
        title: 'Ai chung tình được mãi',
        artist: 'Trung Quân Idol',
        time: '3:52',
        active:false,
        favorite:true,
    },
    {
        id: 1,
        number: '02',
        file: 'ckgmdt.mp3',
        title: 'Có không giữ mát đừng tìm',
        artist: 'Trúc Nhân',
        time: '3:51',
        active:false,
        favorite:true,
    },
    {
        id: 2,
        number: '03',
        file: 'cmbg.mp3',
        title: 'Cơn mưa băng giá',
        artist: 'Bằng Kiều',
        time: '3:20',
        active:false,
        favorite:true,
    },
    {
        id: 3,
        number: '04',
        file: 'd.mp3',
        title: 'Đông',
        artist: 'Trúc Nhân',
        time: '3:24',
        active:false,
        favorite:true,
    },
    {
        id: 4,
        number: '05',
        file: 'dlx.mp3',
        title: 'Đêm lao xao',
        artist: 'Bằng Kiều',
        time: '3:19',
        active:false,
        favorite:true,
    },
    {
        id: 5,
        number: '06',
        file: 'dstld.mp3',
        title: 'Đã sai từ lúc đầu',
        artist: 'Bùi Anh Tuấn-Trung Quân Idol',
        time: '3:19',
        active:false,
        favorite:false,
    },
    {
        id: 6,
        number: '07',
        file: 'hmm.mp3',
        title: 'Hẹn một mai',
        artist: 'Bùi Anh Tuấn',
        time: '3:19',
        active:false,
        favorite:false,
    },
    {
        id: 7,
        number: '08',
        file: 'ttbdty.mp3',
        title: 'Trái tim bên lề',
        artist: 'Bằng Kiều',
        time: '3:19',
        active:false,
        favorite:false,
    },
    {
        id: 8,
        number: '09',
        file: 'v.mp3',
        title: 'Vẽ',
        artist: 'Trúc Nhân',
        time: '3:19',
        active:false,
        favorite:false,
    },
];

